### ISSUE TITLE
Avoid enlarging the image on hover if the image seeker is dragged

### ISSUE THREAD

**Issue by Ottodix** [Wil-B/Biography#3]
Hi,

It seems like a unexpected behavior to me : when you drag the main image seeker, if the main image option "Enlarge on hover" is active, it will still enlarge the image even if you are currently dragging the seeker. For me it's better to disable the "Enlarge on hover" option while dragging, so i've done this modification : 

In move(x, y, click) function of panel.js, line 1135, change from
`if (!ppt.autoEnlarge || click || this.zoom()) return;`
to
`if (!ppt.autoEnlarge || click || this.zoom() || seeker.dn) return;`

**Comment by Wil-B** [comment]
Thanks. I've merged the PR.
